### ISSUE TITLE
[frontend] edit/delete post UI

### ISSUE THREAD

**Issue by kittybest** [Unirep/Unirep-Social#110]
- User can generate the proof of epoch key of the post (or comment)
- Then delete the post (The `hashContent` will be set `0` on-chain)
- But all the comments and votes should still be left

**Comment by ChialiTsai** [comment]
I'm unable to delete the post on staging: https://social-staging.unirep.io

step:
complete a UST, 
go to my page,
find a post, edit -> delete
![image.png](https://images.zenhubusercontent.com/632a7d53a185f62cf181667a/9d3a774e-679b-4bdb-bb0a-ef5e5558f163)

the UI can't delete my post.

**Comment by AnthonyMadia** [comment]
Are you able to delete a post? @ChialiTsai

**Comment by AnthonyMadia** [comment]
Are you able to edit a post? @ChialiTsai
