### ISSUE TITLE
User doesn't know the app can only open in 1 tab

### ISSUE THREAD

**Issue by ChialiT** [Unirep/Unirep-Social#127]
Maybe hard to solve.

Step of procedure:
- open Unirep social in multiple tabs
- login to one of tabs
- observe the other tabs still saying: please sign in
- add sign in string
- UI has no feedback

Expected result:
option 1: if user sign in in one of tabs, the other tabs should also be signed in
option 2: if user sign try to sign in to other open tabs, the UI should have feedback, say: this ID already signed in elsewhere or something similar.

**Comment by kittybest** [comment]
If the user open Unirep Social on just 1 tab, then sign up and open up another tab, it should be logged in status; else, if the user open 2 tabs originally, and sign up in one of the tab, user must refresh other tab and will be logged in. This is also what other website does.
