### ISSUE TITLE
Gas price watcher

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep-Social#13]
The transaction manager has a hardcoded gas price right now. This should be changed to a value that is calculated periodically using the median gas price. Omitting the field and allowing ethers to automatically fill it caused an error for some reason.

It's probably a good idea to do this ourselves anyway so we can in the future do things like optimize away from local highs in the gas markets.

**Comment by ChialiT** [comment]
Won't fix due to sunsetting the project
