### ISSUE TITLE
Add test coverage for Context classes in frontend

### ISSUE THREAD

**Issue by AnthonyMadia** [Unirep/Unirep-Social#134]
[This](https://github.com/Unirep/Unirep-Social/tree/main/packages/frontend/src/context) context is being tested within the current unit tests but does not have isolated unit test coverage. 

Context:
- [X] EpochManager
- [ ] Post
- [ ] Prover
- [ ] Queue 
- [X] Unirep
- [ ] User

**Comment by ChialiT** [comment]
Won't fix due to sunsetting the project
