### ISSUE TITLE
Event synchronization

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep-Social#14]
The backend currently loads all events at once using a `queryFilter` call. This will break after a few hundred events exist for a topic. I solved this problem in zkopru by starting at the block where the contract was created (or the block of the latest event in the DB) and then loading events for a batch of 1000 blocks, then ingesting, then repeat. Once I reach the head block I start a subscription listener. You can see it [here](https://github.com/zkopru-network/zkopru/blob/main/packages/core/src/node/synchronizer.ts#L467). I think we should use a similar strategy for this backend.

**Comment by ChialiTsai** [comment]
@vimwitch can we close this issue? it seems already completed.

**Comment by ChialiT** [comment]
Won't fix due to sunsetting the project.
