### ISSUE TITLE
If user skips Epoch, the application will return error

### ISSUE THREAD

**Issue by ChialiTsai** [Unirep/Unirep-Social#147]
![image.png](https://images.zenhubusercontent.com/632a7d53a185f62cf181667a/1d7eac5d-2015-4877-99c5-f1f8d4451b07)

**Comment by kittybest** [comment]
might be solved by PR #151 , but not sure, should observe

**Comment by ChialiTsai** [comment]
@AnthonyMadia could you help us to verify this one? if its fixed? thank you

**Comment by AnthonyMadia** [comment]
Yea, looks like I do not have this error. In the console, I see that `Epoch x Ended` with `Y {_hex: '0x1e', _isBigNumber: true} ` after the ended message. Nothing about an error in the queue operation for me. @ChialiTsai

**Comment by ChialiTsai** [comment]
Thank you for verifying @AnthonyMadia 
if looks good for you, I'll let u close the ticket, you are our gatekeeper :)
