### ISSUE TITLE
Rep inaccuracy

### ISSUE THREAD

**Issue by ChialiT** [Unirep/Unirep-Social#159]
Not 100% is UI bug or protocol bug.

In the activity, I have calculated that I received 10 boost and 3 squash, but in the side widget, it shows 0
![image.png](https://images.zenhubusercontent.com/632a7d53a185f62cf181667a/b02691ba-a2c8-4d70-911d-7351a439a4fb)
![image.png](https://images.zenhubusercontent.com/632a7d53a185f62cf181667a/609b09aa-efff-4be9-9fab-f1519ef75663)![image.png](https://images.zenhubusercontent.com/632a7d53a185f62cf181667a/c70137d0-8aca-494a-9ba7-bfeddd10be60)![image.png](https://images.zenhubusercontent.com/632a7d53a185f62cf181667a/c1f12ed3-8bd4-4ccd-93cb-49abb625f419)![image.png](https://images.zenhubusercontent.com/632a7d53a185f62cf181667a/b9699726-9e89-4412-aad0-12c2014ec145)
![image.png](https://images.zenhubusercontent.com/632a7d53a185f62cf181667a/c0cc9aa1-7ff9-4caf-93f2-d6c0f87256c1)

also, I haven't get any boost in current epoch, but it displayed that I have 8
![image.png](https://images.zenhubusercontent.com/632a7d53a185f62cf181667a/6ba2e41b-31b3-4a77-a3e9-032e2db0841b)

**Comment by ChialiTsai** [comment]
@AnthonyMadia would you like to add more detail on this one, please? :)

**Comment by AnthonyMadia** [comment]
The bug occurred after a UST. I had 28 rep and after the UST I had 10. Furthermore, the rep disappeared. Here is a video:


https://user-images.githubusercontent.com/78113974/202517259-b52654bf-34e0-4df9-a97a-aae5372ffd52.mp4

**Comment by kittybest** [comment]
https://github.com/Unirep/Unirep-Social/pull/164

**Comment by ChialiT** [comment]
Won't fix due to sunsetting the project
