### ISSUE TITLE
[UI fix] Limit the amount of space a photo upload takes

### ISSUE THREAD

**Issue by AnthonyMadia** [Unirep/Unirep-Social#160]
Photos are currently too large and crowd the comment space section causing poor UI.

Example:

![image](https://user-images.githubusercontent.com/78113974/202348666-4ee2284d-8a97-4600-af1f-c83ac5f207de.png)

**Comment by kittybest** [comment]
what size should it be? I just put it as its original size

**Comment by AnthonyMadia** [comment]
Not exactly sure -- going to play around with it today. I would go with whatever flows correctly and does not impede users from reading comments.

**Comment by ChialiTsai** [comment]
From this screenshot, it looks like we cut off the image?
I think it should have a fixed area to show the image, for ex: 500px x 500px, then based on the image ratio, then display the photo. if an image is very long, then we will show the longest as 500px. if an image is very wide, then the widest goes to 500px.

later we can enhance to view the larger image in a lightbox.

**Comment by AnthonyMadia** [comment]
Yes, I made a PR with the changes I mentioned for a quick fix, but there should be a separate PR that focuses on getting images correct.
