### ISSUE TITLE
URL missing and typo

### ISSUE THREAD

**Issue by aguzmant103** [Unirep/Unirep-Social#161]
**Describe the bug**
URL missing and typo

**To Reproduce**
1. Go to Settings
2. See typo "You can learn more about _Sempahore_ here" 
3. It als doesn´t have a link

**Expected behavior**

**Screenshots**
![Screenshot_106](https://user-images.githubusercontent.com/67167307/203218986-45f17eb0-698c-4d68-b57b-b00018d1579c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ChialiTsai** [comment]
task completed and tested on staging.
