### ISSUE TITLE
Unable to post due of inaccurate rep calculation

### ISSUE THREAD

**Issue by ChialiT** [Unirep/Unirep-Social#165]
**Describe the bug**
<img width="415" alt="image" src="https://user-images.githubusercontent.com/16527634/203458217-8796261a-a35a-47fd-8a52-3d5edfde1c72.png">

**To Reproduce**
Have enough rep-handout and unable to post any post.
No UI feedback to the user, thus very confusing.

**Comment by AnthonyMadia** [comment]
Did you try deleting your anondb and firebase db in the Applications tab, refreshing, and logging in again?

**Comment by ChialiTsai** [comment]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/16527634/203459884-d5fb915b-8a03-4318-bbf1-b7c8bb5d3df1.png">


issue still occur, after cleared all the cached, db..etc.

**Comment by ChialiT** [comment]
Won't fix due to sunsetting the project
