### ISSUE TITLE
Add Topics for Users to Post Under (and Grant Privileges Based On Reputation)

### ISSUE THREAD

**Issue by AnthonyMadia** [Unirep/Unirep-Social#167]
Adding topics will reduce the application from being general.

The topics will be "Foundational Topics" that the users will post under. Some topics (subject to change) are:

- Science & Technology
- Philosophy
- Politics
- Business
- Literature
- Music
- Fitness
- Photography
- News

Because the application is based on gaining reputation, I am proposing we allow users to create their own sub-topics and "Foundational Topics" when they gain a certain amount of reputation (amount is TBD). This adds utility to the reputation because users can do something with it (gain privileges) other than upvote/downvote/comment/post. 

_Note that the "grant privileges" part of this issue can be made into its own issue. I am writing it here for ideation purposes._

Adding topics will change the UI, so I included some initial wireframes [here](https://whimsical.com/topics-wireframe-Bsbxi4onzaA5HLbES4Pzja). 

The topics would be links that link to their own page. For example, clicking on the `Philosophy` topic would link the user to `localhost:3000/philosophy` and a user can post on that page.

**Comment by ChialiTsai** [comment]
I agree. Currently, users feel lack of topics for discussion.
we will include this for v2. Thank you for the proposal, it's very needed.

**Comment by AnthonyMadia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/UniRep-Social-6351a6e18e7a4500115726a9/issues/Unirep/Unirep-Social/167?planning-poker) with Zenhub @0xChiali @CJ-Rose @kittybest @vimwitch @vivianjeng

**Comment by AnthonyMadia** [comment]
The topics can also be user-generated. This is probably a better approach to hard-coding topics.

**Comment by AnthonyMadia** [comment]
To make user-generated topics work well,  search needs to be implemented effectively to find topics users create. After a topic page is found, a user can 'join' a particular topic page. 

Other add-on features would include:
- adding all the topic pages a user joins on a separate page that can be linked to from the landing page
- the landing page would be changed to include only the posts from the relevant topics a user 'joins' or 'follows'

**Comment by CJ-Rose** [comment]
Could we hardcode Foundational Topics in the horizontal nav bar as is currently, and have user-generated Subtopics appear in a drop-down menu under each category? Each Foundational Topic could have a General subheading to start.

I think letting users start new topics by spending rep would be a great bonus in adding utility and increasing engagement.
