### ISSUE TITLE
Reduce Time of UST POST Request

### ISSUE THREAD

**Issue by AnthonyMadia** [Unirep/Unirep-Social#177]
Currently, it takes ~20s for a UST POST request to be completed.

Screenshot of fetch requests on Chrome Network tab:
![networkrequests](https://user-images.githubusercontent.com/78113974/205102795-72a513e9-0e8c-4dc0-a8f8-a5a610dcda6c.png))

Machine: 
Linux x86_64

**Comment by ChialiT** [comment]
Won't fix due of sunsetting the project.
