### ISSUE TITLE
[frontend] user info page should load records after refreshing

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep-Social#178]
**Describe the bug**
The **boost** and **squash** field become **+0** and **-0** after refreshing the user info page
and also **Activity** in user info page

**Expected behavior**
`getUserData` after refreshing
https://github.com/Unirep/Unirep-Social/blob/ea5de0408bccabc45b97c585c9e23c503bb4e4a1/packages/frontend/src/pages/userPage/userPage.tsx#L143-L153

**Screenshots**

https://user-images.githubusercontent.com/17507085/205879565-db9e186e-4c4c-4399-994d-b46fe464306d.mov

**Comment by kittybest** [comment]
also after user signing in
