### ISSUE TITLE
Negative Reputation Proof Verification

### ISSUE THREAD

**Issue by kittybest** [Unirep/Unirep-Social#180]
**Describe the bug**
If I send wrong negative reputation proof to the backend to verify, it should return error.

**To Reproduce**
1. userState.genNegRepProof(attesterId, [reputation with negative number such as -7])
2. verify the proof with `verifyNegRepProof`
3. it passed

**Expected behavior**
should not pass

**Screenshots**
![image](https://user-images.githubusercontent.com/9023842/206198479-3164636b-944e-4ffc-8e43-524b89d2b532.png)
proof is actually look like this, with very large negRep number since I put -10 inside

**Comment by kittybest** [comment]
![image](https://user-images.githubusercontent.com/9023842/206199081-a1c056e5-1d4b-4484-b757-da1a13fba687.png)
the negative is normal while sending "positive" number of negative reputation to the proof. (see `negRep` in the picture)

**Comment by ChialiT** [comment]
Won't fix due to sunsetting the project

**Comment by vivianjeng** [comment]
v2 solved it
I added a test here
https://github.com/Unirep/Unirep-Social/blob/85d1f226f78ab4019acf3eaa67bac60cdb2e0637/packages/circuits/test/proveAction.test.ts#L478-L500
