### ISSUE TITLE
New post is not appeared on the top of the `New` feed

### ISSUE THREAD

**Issue by kittybest** [Unirep/Unirep-Social#182]
**Describe the bug**
New post is not appeared on the top of the `New` feed

**To Reproduce**
1. Sign up 2 different account and open two incognito windows
2. post in one of the window
3. press on feed tabs to change and reload posts

**Expected behavior**
While click on `new` tab, the newest post should appear on top of the page

**Screenshots**
<img width="762" alt="image" src="https://user-images.githubusercontent.com/9023842/206207850-80bf58ab-a8a5-4f49-868a-81242c4836ae.png">

**Comment by ChialiT** [comment]
Won't fix due to sunsetting the project
