### ISSUE TITLE
[circuits] subsidy proof should include graffiti proof

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep-Social#197]
if user uses subsidy to post/comment, he can choose whether to show the username

**Comment by ChialiT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/UniRep-Social-6351a6e18e7a4500115726a9/issues/Unirep/Unirep-Social/197?planning-poker) with Zenhub @kittybest @AnthonyMadia @CJ-Rose @vimwitch @vivianjeng @yuriko627

**Comment by kittybest** [comment]
We should discuss about the mechanism we're going to use in the future application -- still subsidy kind of things? or we'll discover a better solution to solve the problem?
