### ISSUE TITLE
Circom 2.1.0 Anonymous Components and Tuples

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep-Social#209]
Same as this issue
https://github.com/Unirep/Unirep/issues/530

**Comment by saeyoon17** [comment]
Hi, @vivianjeng, I am a student participating in PSE's Summer Contribution Camp. 
It seems like the actionProof.circom is in the refactored form, so I was just wondering if this issue is still valid. 
Would there be anything else I missed?

**Comment by vivianjeng** [comment]
Hi @saeyoon17 
This is already refactored, so I will close this issue.
Thank you for your interest.
