### ISSUE TITLE
[backend] Add a route to request a username

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep-Social#40]
We need a route to request a username. This could be `/api/usernames POST`.

- The route should accept and verify a ZK proof proving the epoch key and current graffiti pre-image
- The route should accept a username that is being requested

The route should then check if the username is free, and if it is use the `setUsername` function in the unirep social contract to claim it. The username will need to be hashed with poseidon offchain so the hash is what is submitted in the contract call.

**Comment by yuriko627** [comment]
@vimwitch what should include in the response? I'm currently thinking 
- hash of transaction to setUsername
- current epoch

**Comment by vimwitch** [comment]
We don't want to return the current epoch because the backend isn't a source of truth for that. The frontend loads the current epoch directly from the blockchain.

Returning just the transaction hash is usually fine. We want to load most things from the blockchain, so we'll wait for the attestation event in the synchronizer on the frontend.
