### ISSUE TITLE
[Design] Easily sign up

### ISSUE THREAD

**Issue by ChialiTsai** [Unirep/Unirep-Social#45]
Related to: 

- [ ] #44 
- [x] #36

**Comment by ChialiTsai** [comment]
complete design at: https://www.figma.com/file/wotPPn36lbheCaGHTlPX0N?node-id=3478:40214#244889650

@kittybest @vimwitch  have a look.
if flow, design look ok, i will mock up the mobile view.

**Comment by vimwitch** [comment]
LGTM

**Comment by ChialiTsai** [comment]
Modify the intro and welcome msg to centered aligned
added the :hover style to figma
