### ISSUE TITLE
Rich Text Editor: collaborate with Tsukino

### ISSUE THREAD

**Issue by ChialiT** [Unirep/Unirep-Social#51]
As an user, I want to edit my post or comment with freely styling to make my article looks great

- collaborate with tsukino
- integrate to Unirep-Social and adjust the styling

**Comment by ChialiTsai** [comment]
related to #50

**Comment by ChialiT** [comment]
Won't fix due to sunsetting the project.

**Comment by kittybest** [comment]
I think we can still keep this to remind myself 😅

**Comment by ChialiT** [comment]
It's ok, I will remember it for you XD
