### ISSUE TITLE
[Design] New rep system interaction

### ISSUE THREAD

**Issue by ChialiTsai** [Unirep/Unirep-Social#57]
Iterate the UI to provide clarity for user when they interact with the app

relate to: https://github.com/Unirep/Unirep-Social/issues/76

**Comment by ChialiTsai** [comment]
@vimwitch will need you to help understand the logic of subsidy epoch key

**Comment by vimwitch** [comment]
Ah the subsidy epoch key isn't really a thing. We just use the first epoch key for spending subsidy.

**Comment by ChialiTsai** [comment]
https://www.figma.com/file/wotPPn36lbheCaGHTlPX0N?node-id=3806:40352#261678010

touch points:
- home (side widget has updated)
- onboarding (msg has updated)
- making a post or comment, the interaction kit has been updated
- boost/squash template


@kittybest 
@vimwitch if you want to have a look, much apperciated.
