### ISSUE TITLE
[frontend] user transition interface shouldn't block the whole screen

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep-Social#83]
As a user I want to keep reading the website without having to UST if I don't want to.

**Comment by ChialiTsai** [comment]
![Image](https://user-images.githubusercontent.com/16527634/188501000-73e1ea09-4f69-4390-ae86-dc549f510dc6.png)

https://www.figma.com/file/wotPPn36lbheCaGHTlPX0N?node-id=3806:41564#260068565
